# define detector material before run initialization
/control/execute macros/geometry_options/FLArE_only_newBabyMIND.mac
/det/saveGdml false

/run/initialize
/random/setSeeds 324199 420475

# define particle gun options
/gen/select gun
/gps/verbose 0
/gps/pos/type Point
/gps/pos/centre 0 0 7.8 m
/gps/direction 0 0 1
/gps/particle mu-
/gps/ene/mono 5.0 GeV

/out/fileName mu-_5GeV_newBabyMIND.root

# shoot 1 particles
/run/beamOn 50
