# define detector material before run initialization
/control/execute macros/geometry_options/FPF_hall_Option1a_FORMOSAlast_BabyMIND.mac

/run/initialize
/random/setSeeds 324199 420475

# define genie input options
/gen/select background
/gen/bkg/backgroundInput ../backgrounds/background_input.root
/gen/bkg/backgroundWindow 187.5 us

# define output options
/out/flare/save3DEvd false
/out/flare/save2DEvd false

/out/addDiffusion false
/out/fileName test_backgrounds.root

# store and save trajectories for EVD
/tracking/storeTrajectory 1
/out/saveTrack true

# shoot background equivalent to 1 "spill"
/run/beamOn 1
