# define detector material before run initialization
/control/execute macros/geometry_options/FLArE_only_BabyMIND.mac
/det/flare/useNativeG4Scorer true

/run/initialize
/random/setSeeds 324199 420475

# define genie input options
/gen/select background
/gen/bkg/backgroundInput ../backgrounds/background_input.root
/gen/bkg/backgroundWindow 187.5 us

# define output options
/out/flare/enableOutput false
/out/faser/actsHits false
/out/fileName test_flare_score.root

# store full trajectories for EVD
/out/saveAllParticles false
/out/saveTrajectories false

# shoot background equivalent to 1 "spill"
/run/beamOn 1
