# define detector material before run initialization
/control/execute macros/geometry_options/FASER2_only.mac

/run/initialize

# define hepmc input options
/gen/select hepmc
/gen/hepmc/hepmcInput /afs/cern.ch/user/b/bewilson/work/public/hepmc/events_14TeV_m0.3548GeV_c1e-06_to_mu_mu_s1.hepmc3
/gen/hepmc/vtxOffset 0 0 1500 mm
/gen/hepmc/placeInDecayVolume true

# define output options
/out/save3DEvd false
/out/save2DEvd false

/out/addDiffusion false

/out/fileName test_dark_photon_hepmc.root

# shoot 5 particles
/run/beamOn 5
