# define detector material before run initialization
/control/execute macros/geometry_options/FPF_hall_Reference.mac

/run/initialize
/random/setSeeds 324199 420475

# define genie input options
/gen/select genie
/gen/genie/genieInput /eos/user/m/mvicenzi/genie/nutau_bai_ar40_e2000.gst.root
/gen/genie/genieIStart 5

# define output options
/out/flare/save3DEvd false
/out/flare/save2DEvd false

/out/flare/addDiffusion false
/out/fileName test_genie_nutau.root

# shoot 5 particles
/run/beamOn 5
